# Generated by Django 3.2.14 on 2022-08-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
