# Generated by Django 3.2.14 on 2022-08-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_solves'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solves',
        ),
    ]
