# Generated by Django 3.2.14 on 2022-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='Picture'),
        ),
    ]
