# Generated by Django 3.2.14 on 2022-08-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blogpost_blog_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_post',
            new_name='BlogPost',
        ),
    ]
